### ISSUE TITLE
Your PRs are welcome!

### ISSUE THREAD

**Issue by nearbyplayer** [esx-framework/esx-framework.github.io#16]
@jonassvensson4 your PRs are more than welcome! So please do send them in. Just make sure you utilize the development branch!

**Comment by nearbyplayer** [comment]
Also please join our Discord if you aren't already, https://discord.me/esx

**Comment by jonassvensson4** [comment]
Yes I will! 

I think I deleted everything that you requested? Let me know if I missed something, it's early in the morning after all

**Comment by nearbyplayer** [comment]
The esx-community account is still active, this is the last piece in the puzzle, thank you very much!

**Comment by nearbyplayer** [comment]
Here is the link: https://github.com/esx-community

**Comment by jonassvensson4** [comment]
It has been deleted

**Comment by nearbyplayer** [comment]
Thank you very much, I look forward to your PRs to this repo! I'll be closing this now, hopefully you'll join the Discord as well!
